### ISSUE TITLE
Android Studioのインストール

### ISSUE THREAD

**Issue by yukinkomob** [yukinkomob/GymAppMgmt#1]
## Why

- Android開発のベースとなる環境を用意する

## What

- 下記の説明に沿ってAndroid Studioをインストールする
  - 不明点などは質問してください

https://developer.android.com/studio?gclid=Cj0KCQiA6fafBhC1ARIsAIJjL8lJZzpned3_qH43gRKQRKmLwpY5Uo931DqmkHQ3UyCOD1eB8jse4BIaArhYEALw_wcB&gclsrc=aw.ds

## Try

- Android Studioのバージョンを確認する
- Android Studioが起動したらスクリーンショットを撮影して、コメントとして貼り付けてみてください

**Comment by yukinkomob** [comment]
@takuto2302 

こちらはレビュー依頼ということでしょうか？
下記を試してみて頂けますか

> Android Studioが起動したらスクリーンショットを撮影して、コメントとして貼り付けてみてください

**Comment by takuto2302** [comment]
こういう形の報告で大丈夫でしょうか。


![Image](https://user-images.githubusercontent.com/125285999/222614755-acae5b17-a4bf-474e-816a-39be0299cee9.png)
![Image](https://user-images.githubusercontent.com/125285999/222614754-42daccfd-f28b-4d5e-8a0d-fcc06e2dd668.png)

**Comment by yukinkomob** [comment]
LGTM👍
