### ISSUE TITLE
TODOアプリ開発

### ISSUE THREAD

**Issue by yukinkomob** [yukinkomob/GymAppMgmt#10]

**Comment by yukinkope** [comment]
test

**Comment by takuto2302** [comment]
https://github.com/GhExercises/ToDoApp

pushしましたので確認お願いします。

**Comment by yukinkomob** [comment]
確認が遅くなり、申し訳ありません。
ご対応ありがとうございます。
下記、確認いたしました。問題ございません！

https://github.com/yukinkomob/GymAppMgmt/assets/3205581/0e5096c5-811e-47ab-a3ba-d935c4b7f5b3



ブラッシュアップポイントとしていくつか記載しておきます。
* 新規登録ボタンがないため、新しいタスクを登録する際にアプリの再起動が必要になっている
  - 右下に＋のフローティングボタンなどを用意してどの画面からでも利用可能な形にするのもありだと思います
![image](https://github.com/yukinkomob/GymAppMgmt/assets/3205581/e1d23d2d-e576-47e0-ac2e-01e598098478)
* タスク登録後に登録した内容が残っているため、ボタンを連打すると同じタスクが複数登録されてしまう
  - 登録後に内容をクリアしたり、または一覧画面に遷移するなどでも良いと思います

以上、修正する必要はないですが、ご参考までに

**Comment by yukinkomob** [comment]
https://github.com/yukinkomob/GymAppMgmt/assets/3205581/0e5096c5-811e-47ab-a3ba-d935c4b7f5b3

**Comment by takuto2302** [comment]
なるほどですね！そのフローティングボタンを作ったことがないので作り方を学習しておきます！
