### ISSUE TITLE
PCのメモリ状態を確認する

### ISSUE THREAD

**Issue by yukinkomob** [yukinkomob/GymAppMgmt#14]
## Why

- メモリ増設が可能かどうか知りたい

## What

- 確認用のソフトCPU-Zを用いて、PCのメモリスロットの状態を確認する
  - CPU-Zの使い方
    - https://www.pc-master.jp/mainte/cpu-z.html
  - スクリーンショットを撮影してコメントとして貼り付けてください
- 増設可能なようであれば、増設用のメモリを送付いたします

**Comment by yukinkomob** [comment]
下記のような画面

![Image](https://user-images.githubusercontent.com/3205581/222453831-39e7de9e-7cf9-4d8c-8f53-30feccbfdf1c.png)

**Comment by yukinkomob** [comment]
下記の画面でSlotに空きがあるかどうかが知りたいです。

![Screenshot 2023-03-02 at 23 22 05](https://user-images.githubusercontent.com/3205581/222454979-eaef2b39-aff7-4360-8719-cf34043f3230.png)

**Comment by takuto2302** [comment]
memory

![Image](https://user-images.githubusercontent.com/125285999/222617474-ce4446de-8425-4e60-acbb-f7d91c07d9e3.png)

**Comment by takuto2302** [comment]
spd slot 
これで大丈夫でしょうか。

![Image](https://user-images.githubusercontent.com/125285999/222617527-aa4d21db-2fa1-43a9-b491-3d27c5ab666c.png)



![Image](https://user-images.githubusercontent.com/125285999/222617529-bff621b2-56ec-4202-9a50-b9a0d002704e.png)

**Comment by yukinkomob** [comment]
@takuto2302 
メモリスロットが空いているみたいですね。時間のある時にノートPC（ですかね？）のメモリスロットを開けてみて、実際に空きがあるか確認することは可能でしょうか？

**Comment by takuto2302** [comment]
ノートPCです！
1スロット空いてますね。

![Image](https://user-images.githubusercontent.com/125285999/222625848-da352962-6170-45b4-a5b5-51839336f7da.png)
