### ISSUE TITLE
シミュレータの設定

### ISSUE THREAD

**Issue by yukinkomob** [yukinkomob/GymAppMgmt#2]
## Why

- Android開発環境でアプリを動作する環境を用意

## What

- Android StudioでAVDの設定を行う（参考URLを参照）
- エミュレータを起動する
- インストール済みのアプリの起動などを行ってみる
- その他、エミュレータの基本的な操作などを確認する

## Try

- エミュレータを起動したらスクリーンショットを撮影し、コメントとして貼り付けてみてください

## 参考

[Android] エミュレータの作成、設定
https://akira-watson.com/android/avd-manager.html

**Comment by yukinkomob** [comment]
@takuto2302 
こちらもレビュー依頼ということでしょうか？

**Comment by takuto2302** [comment]
動きました！
カメラを起動した画面のスクショを添付してます。
ご確認のほど、宜しくお願いいたします。
![Image](https://user-images.githubusercontent.com/125285999/222998657-939e2315-b447-437b-9c76-8dd691cc7562.png)

**Comment by yukinkomob** [comment]
ご対応ありがとうございます！
スクショ確認しました。ちゃんと動作しているようですので、OKです！
