### ISSUE TITLE
サンプルアプリの作成・起動

### ISSUE THREAD

**Issue by yukinkomob** [yukinkomob/GymAppMgmt#3]
## Why

- アプリの作成準備を可能にしたい

## What

- アプリのプロジェクトを作成する
  - 参考
    - プロジェクトを作成する  |  Android デベロッパー  |  Android Developers
      - https://developer.android.com/studio/projects/create-project?hl=ja
    - KotlinではなくJavaを選択するように注意してください
- アプリをビルドする
- アプリをエミュレータで起動する
- エミュレータ上でアプリの動作を確認してみる

## Try

- 下記のタスクにてサンプルアプリのコードをGitHubに登録してみてください！
  - https://github.com/yukinkomob/GymAppMgmt/issues/11
- サンプルアプリのレポジトリが出来たら、詳細なIssueをそちらに登録しますので、基本的な機能を試していただけるとありがたいです

**Comment by takuto2302** [comment]
サンプルアプリ（ストップウォッチ）を作成してます。
Githubにpushしてますのでご確認お願いいたします。
Githubの使い方も熟知しておらず何かありましたら何なりと申し付け下さい。
またネットで調べながら作成したため、
何も見ず1から100まで作れと言われたら今の実力的には大変厳しいです。

## 下記Github 

187ffc3fd603919cee1f65f0998037f275cfeea7

## スクリーンショット
![Image](https://user-images.githubusercontent.com/125285999/226250350-62d1e72a-feba-471b-91bd-49da26c6d03b.png)

**Comment by yukinkomob** [comment]
@takuto2302 
いえいえ、ここまで作って頂いてありがとうございます！
このタスクの目的は、Android Studioでプロジェクトの作成を経験して頂くことと、それをGitHubレポジトリとして登録して頂くことのみを考えておりましたので、サンプルアプリの中身については、デフォルトのままで問題ありません。
こちらでOKです！

**Comment by yukinkomob** [comment]
@takuto2302 
作業していて不明点などありましたら、GitHubまたはSlackの方でご確認ください。可能な時間帯に返信させて頂くようにいたします。

**Comment by takuto2302** [comment]
ありがとうございます！
一人前になるのは厳しいかもしれませんが、
早くお力になれるよう頑張ります。

**Comment by yukinkomob** [comment]
@takuto2302 

ありがとうございます！
今回のストップウォッチアプリについて、下記のワークスペースにレポジトリを作成して、コミットをお願いできますでしょうか？

https://github.com/GhExercises
レポジトリ名：StopWatchApp

GymAppMgmtのレポジトリに登録されていないソースコードを取得するには、下記の箇所からZipファイルを取得することで可能です
取得したファイルを上記のStopWatchAppに登録してみてください

![Screenshot 2023-03-20 at 14 35 46](https://user-images.githubusercontent.com/3205581/226255238-cbaf5891-6337-4972-909c-326257175741.png)

**Comment by yukinkomob** [comment]
@takuto2302 

手順としては、下記のようなイメージです

* GymAppMgmtのレポジトリのソースコードをzipで取得する
* zipファイルを解凍して、ソースコードを取得可能な状態にする
* GhExercisesワークスペースにレポジトリStopWatchAppを作成する
* StopWatchAppをgit cloneする
* ローカルのStopWatchAppに解凍したソースコードを移動する
* ソースコードをgit commitする
* git pushしてGitHub上のレポジトリに反映する

**Comment by takuto2302** [comment]
ご親切にありがとうございます。

git cloneではなく解凍したデータをそのままpushしてしまったのですが
大丈夫でしょうか。
お手数ですが、ご確認お願いします。
https://github.com/orgs/GhExercises/repositories

**Comment by yukinkomob** [comment]
ご対応ありがとうございます
問題ありません！
