### ISSUE TITLE
Paizaへのアカウント登録

### ISSUE THREAD

**Issue by yukinkomob** [yukinkomob/GymAppMgmt#4]

**Comment by yukinkomob** [comment]
@takuto2302 
こちらは登録完了ということでしょうか？

**Comment by takuto2302** [comment]
paizaへの登録完了してます。

![Image](https://user-images.githubusercontent.com/125285999/222615412-86797b16-6662-4dcd-b543-db0e1727ff9e.png)

**Comment by yukinkomob** [comment]
LGTM!

**Comment by yukinkomob** [comment]
LGTMはGitHubレビューで慣習的に使われる応答で、「私にとってはいいと思えるよ」くらいの曖昧な意味なのですが、このPJでもレビュー承認の応答として使わせてもらおうと思います
慣れないと変な感じがすると思いますが^^

LGTM (Looks Good To Me - 良さそうだね) がなぜレビュー承認に使われるのか - Qiita
https://qiita.com/e99h2121/items/072fa31827bf4591d799

**Comment by takuto2302** [comment]
なるほど！大変勉強になります！ありがとうございます！

Githubに登録していたメールアドレスをチェックする習慣がなかったもので
昨日からここでコメント頂いた件に関してのレスポンスが遅くなってしまい
申し訳ないです。勤務時間帯はここのコメントチェックと合わせて登録アドレスのメールチェックも
行うようにします！
