### ISSUE TITLE
Paiza Dランク問題を通したJava言語での演習

### ISSUE THREAD

**Issue by yukinkomob** [yukinkomob/GymAppMgmt#5]

**Comment by yukinkomob** [comment]
@takuto2302 

Dランクの問題の解答状況を教えてください

**Comment by takuto2302** [comment]
どの画面が分からずこのステータス画面でよろしいですか？
またCランクスキルチェックについては、スキルチェックは出来ておらず
問題集での勉学のみとなってます。
何回か挑戦しましたが、単純にプログラミング能力以前の数学の知識が不足していたように感じましたので教本の方を優先して勉強しておりました。

![Image](https://github.com/yukinkomob/GymAppMgmt/assets/125285999/78479e54-30be-4708-876a-8f1c0110af92)

**Comment by yukinkomob** [comment]
ありがとうございます。その学習方針で良いと思います。
D問題は割と解決しやすいので、そちらを全て解いてからC問題でも良いかも知れません。
（私も最初やった時はそうしました）
C問題はD問題2~3個の組み合わせといった形で出てくるので、多少複雑に見えるかも知れません。
機会があれば、C問題を一緒に解く形でペアプログラミングをやってみましょう。
おそらく練習問題であれば規約にも違反しないはずです。
