### ISSUE TITLE
通知アプリの実装

### ISSUE THREAD

**Issue by yukinkomob** [yukinkomob/GymAppMgmt#6]

**Comment by takuto2302** [comment]
通知権限の設定が出来ましたのでご確認お願いします。

https://github.com/GhExercises/NotificationApp

**Comment by takuto2302** [comment]
何故かmainにpush出来ず一旦ブランチ切ってpull requestからmargeしてます。

**Comment by yukinkomob** [comment]
> 何故かmainにpush出来ず一旦ブランチ切ってpull requestからmargeしてます。

mainブランチにpushする場合、force pushが必要になるかも知れないですね（--forceを付けてgit push）

また、mainブランチ向けにforce pushを防ぐ（pull requestを介してしかpushできないようにする）仕組みもあり、下記のところから参照できるようです。ご参考まで...

![Screenshot 2023-03-24 at 11 08 56](https://user-images.githubusercontent.com/3205581/227406304-ca9649a6-f1c1-4d06-81cc-781dbbe240c3.png)

**Comment by takuto2302** [comment]
なるほど！
確かにもし間違ったコードをmainにpushされたら迷惑かかりますね！
ありがとうございます。

**Comment by yukinkomob** [comment]
@takuto2302 
ご対応ありがとうございます
問題ありません！
