### ISSUE TITLE
カレンダーアプリの実装

### ISSUE THREAD

**Issue by yukinkomob** [yukinkomob/GymAppMgmt#8]

**Comment by takuto2302** [comment]
コピペですが、カレンダーアプリ実装してます。
色々エラーが出て多少変更してますが。。
ご確認お願いします。

https://github.com/GhExercises/CallendarApp/tree/main

## 下記参考したURL
https://qiita.com/Sab_swiftlin/items/0993c489e7ef1c0f969d

**Comment by yukinkomob** [comment]
確認が遅くなり申し訳ありません。
動作など問題ないと思います！ご対応ありがとうございました🙏

https://github.com/yukinkomob/GymAppMgmt/assets/3205581/40476fe2-89df-4ac1-a246-3dbf2f26e18e
